# Generated by Django 4.2.2 on 2023-06-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userregister_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='profilePic',
        ),
        migrations.AlterField(
            model_name='userregister',
            name='password1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='password2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
