# Generated by Django 4.2.2 on 2023-06-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_userregister_profilepic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='customers_pic/'),
        ),
    ]
