# Generated by Django 4.2.2 on 2023-07-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_userregister_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='profRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('fullAddress', models.CharField(max_length=50)),
                ('profilePic', models.ImageField(null=True, upload_to='prof_pic/')),
                ('password1', models.CharField(max_length=30, null=True)),
                ('password2', models.CharField(max_length=30, null=True)),
                ('service_selection', models.BooleanField()),
                ('working_location', models.BooleanField()),
                ('experience', models.IntegerField()),
                ('training_certificate', models.ImageField(null=True, upload_to='training_certificates/')),
            ],
        ),
    ]
